### ISSUE TITLE
possibility to get raw point cloud from photoneo with python wrapper

### ISSUE THREAD

**Issue by kaixin-bai** [kevinzakka/pyphoxi#1]
Thanks for your great work! I just wonder if it is possible to get raw point cloud from photoneo with python wrapper? I have tried to generate point cloud from depth image and find that the raw depth image is uint milimeter but the point cloud is with float milimeter, so for some reasons i cannot use the point cloud generated by depth image because it is not accurate. Thanks

**Comment by kevinzakka** [comment]
Should be pretty straightforward to edit the C++ file to recover the point cloud. I'd start with enabling it here: https://github.com/kevinzakka/pyphoxi/blob/master/pyphoxi/phoxi.cpp#L163 and then sending it through the TCP buffer and reconstructing on the python end. I unfortunately do not have a PhoXi sensor anymore so I can't test any changes I make.

I'm also not exactly sure why you can't recover an accurate point cloud from the rgb and depth frames. The depth data is in meters and given the camera intrinsics and pose, you should be able to backproject to obtain the points.

**Comment by kaixin-bai** [comment]
Thanks for your reply! I have double checked the depth image and find that there's no problem to backproject to point cloud

**Comment by kevinzakka** [comment]
@kaixin-bai Awesome, glad to hear that.
