### ISSUE TITLE
How to use the "Trigger scan" mode?

### ISSUE THREAD

**Issue by kaixin-bai** [kevinzakka/pyphoxi#2]
if it is possible to switch "Free run" mode to "Trigger scan" mode?

**Comment by kevinzakka** [comment]
Hey @kaixin-bai,

I recall having a lot of issues with the trigger scan mode like the sensor refusing to send packets after ~15k frames. Switching to free run mode ended up solving the issue. If you're inclined on using trigger scan mode, you should modify the following: https://github.com/kevinzakka/pyphoxi/blob/master/pyphoxi/phoxi.cpp#L154
